config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root to: "pages#home"

  resources :fidelity_programs do
    resources :rewards
    resources :inscriptions do
      resources :participations
    end
  end

  # --------------Route Fidelty Programme-----------------
  get "/customers", to: "fidelity_programs#show_clients", as: :customers
  get "/subscribe", to: "inscriptions#new", as: :subscribe
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/status", to: "inscriptions#status", as: :status_profile
  get "/etablissement", to: "pages#etablissement", as: "etablissement"
  get "/validations", to: "pages#validations", as: "validations"
  get "/settings", to: "pages#settings", as: "settings"
  get "/landing", to: "pages#landing", as: "landing"

  # --------------Route Customers-----------------

  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_scans", to: "pages#customers_scans", as: :customers_scans
  get "/customers_etablissement", to: "pages#customers_etablissement"

  # --------------Route Participation-----------------
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_rewards", to: "pages#customers_rewards", as: :customers_rewards
  get "/customers_etablissement", to: "pages#customers_etablissement"

  # --------------Route Participations-----------------
  post "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_rewards", to: "participations#redeem", as: :redeem_points
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/history", to: "inscriptions#history", as: :history
end

app/views/shared/_back_button.html.erb
<div class="sih-link">
  <i class="fa-solid fa-chevron-left"></i>
  <%= link_to "Retour", :back, class: "back-btn" %>
</div>

app/views/shared/_burger_menu.html.erb
<div data-controller="burger" class="burger-container">
  <div class="burger-back">
    <div class="burger-btn" data-action="click->burger#toggle">
      <i class="fa-solid fa-bars icon-burger" ></i>
    </div>
      <nav id="burger-menu" data-burger-target="menu" >

        <div class="close-container">
          <i class="fa-solid fa-xmark close-btn" data-burger-target="close" data-action="click->burger#close" ></i>
        </div>

        <div class="links-container">
          <div class="link-container">
            <i class="fa-solid fa-gift icon-link"></i>
            <%= link_to "Mes récompenses", customers_rewards_path,data: { action: "click->burger#close" }, class:"link-nav" %>
          </div>
          <div class="link-container">
            <i class="fa-solid fa-book icon-link"></i>
            <%= link_to "Mes programmes",  root_path,data: { action: "click->burger#close" }, class:"link-nav" %>
          </div>
          <div class="link-container">
            <i class="fa-solid fa-clock icon-link"></i>
            <%= link_to "Mon historique ", history_path(@fidelity_program, @inscription),data: { action: "click->burger#close" }, class:"link-nav" %>
          </div>
        </div>

        <div class="logout">
          <%= link_to "Se déconnecter", destroy_user_session_path, data: {action: "click->burger#close", turbo_method: :delete}, class: "dropdown-item" %>
        </div>
      </nav>
   </div>
  </div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-text">
    <h1>LOOPS. <span>Manager</span></h1>
  </div>
  <div class="header-icon">
    <div class="icon-container">
      <i class="fa-solid fa-bell icon"></i>
    </div>
    <div class="avatar-container">
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    </div>
  </div>
</div>

app/views/shared/_header_customer.html.erb
<div class="header">
  <div class="header-text">
    <h1>LOOPS.</h1>
  </div>
  <div class="header-icon">
    <div class="icon-container">
      <i class="fa-solid fa-bell icon"></i>
    </div>
    <div class="avatar-container">
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="side-bar" data-controller="navbutton" >
  <div class="side-container">
    <div class="section active" data-action="click->navbutton#change" data-navbutton-target="navElement">
      <div class="nav-i-container">
        <i class="fa-solid fa-house nav-icon"></i>
      </div>
      <%=  link_to "Accueil", pages_home_path, class:"link", data: {turbo: :false} %>
    </div>
    <div class="section" data-action="click->navbutton#change" data-navbutton-target="navElement">
      <div class="nav-i-container">
        <i class="fa-solid fa-handshake nav-icon"></i>
      </div>
      <% if current_user.fidelity_program.nil? %>
        <%= link_to "Programme", landing_path, class:"link", data: {turbo: :false} %>
      <% else %>
        <%= link_to "Programme", fidelity_program_path(current_user.fidelity_program), class:"link", data: {turbo: :false} %>
      <% end %>
    </div>
    <div class="section" data-action="click->navbutton#change" data-navbutton-target="navElement" >
      <div class="nav-i-container">
        <i class="fa-solid fa-circle-user nav-icon"></i>
      </div>
        <%= link_to "Clients", customers_path, class:"link", data: {turbo: :false} %>
    </div>
  </div>
</div>