config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root to: "pages#home"

  resources :fidelity_programs do
    resources :rewards
    resources :inscriptions do
      resources :participations
    end
  end

  # --------------Route Fidelty Programme-----------------
  get "/customers", to: "fidelity_programs#show_clients", as: :customers
  get "/subscribe", to: "inscriptions#new", as: :subscribe
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/status", to: "inscriptions#status", as: :status_profile
  get "/etablissement", to: "pages#etablissement", as: "etablissement"
  get "/validations", to: "pages#validations", as: "validations"
  get "/settings", to: "pages#settings", as: "settings"
  get "/landing", to: "pages#landing", as: "landing"

  # --------------Route Customers-----------------

  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_scans", to: "pages#customers_scans", as: :customers_scans
  get "/customers_etablissement", to: "pages#customers_etablissement"

  # --------------Route Participation-----------------
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_rewards", to: "pages#customers_rewards", as: :customers_rewards
  get "/customers_etablissement", to: "pages#customers_etablissement"

  # --------------Route Participations-----------------
  post "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_rewards", to: "participations#redeem", as: :redeem_points
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/history", to: "inscriptions#history", as: :history
end

app/views/pages/customers_rewards.html.erb
<%= render 'shared/burger_menu' %>

<div class="s-i-head">
  <div class="container">
    <div class="sih-link">
    <i class="fa-solid fa-chevron-left"></i>
    <%= link_to "Retour", root_path, class: "back-btn" %>
    </div>

    <div class="sih-info">
    <h1>Mes récompenses</h1>
    <p>Retrouvez la liste des récompenses proposées par le programme</p>
    </div>
  </div>
</div>

<div id="points-reward" >

  <div id="reward-container">

    <div id="rc-title">
      <p>Mes points</p>
    </div>
    <div id="rc-sum">
      <% @inscription.participations.each do |p| %>
        <% @sum += p.points %>
      <% end %>
      <p data-redeem-points-target="balance"><%= @sum %>
      <span class="mdi--star-four-points-circle"></span></p>
    </div>

  </div>

  <div id="reward-cards" data-controller="reward-card">
    <% @rewards.each do |r| %>
    <div class="reward-card" data-action="click->reward-card#cardClick" >
      <div class="ri-reward-img">
        <div class="ri-image-wrapper">
            <%= image_tag r.name.downcase == "boisson" ? "boisson.png" : "sushi2.png" %>
          </div>
      </div>
      <div class="reward-info">
        <div class="ri-name">
          <p><%= link_to "#{r.name}", fidelity_program_reward_path(@fidelity_program, r), class: "td-none", data: { reward_card_target: "link" } %></p>
        </div>
        <div class="ri-description">
          <p><%= r.description %></p>
        </div>
      </div>
      <div class="reward-points">
        <p><%= r.points_required %></p>
        <span class="mdi--star-four-points-circle">
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/customers_scans.html.erb
<div id="cs-mc">
    <div id="scan-container">
      <div id="scan-info">
        <div id="scan-txt">
        <h1>Transaction validée</h1>
        </div>
        <div id="scan-points">
        <h1>+<%= @inscription.participations.last.points %></h1>
        </div>
        <div id="scan-logo">
        <div id="scan-img"><i class="fa-sharp fa-solid fa-check"></i></div>
      </div>
    </div>

      <div id="scan-btn">
        <%= link_to "Récupérer", fidelity_program_inscription_path(@fidelity_program, @inscription), class: "td-none" %>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<% if current_user.role == "merchant" %>

<div class="main-home">
  <div class="text-home">
    <p>Hello, <span><%= current_user.name %></span></p>
    <br>
    <h1>Résumé du jour</h1>
  </div>

  <div class="cards">
    <div class="card">
      <span>Clients Inscrits</span>
      <% if @fidelity_program.present? %>
        <p><%= @fidelity_program.inscriptions.count %></p>
      <% else %>
        <p>0</p>
      <% end %>
      <span></span>
    </div>
    <div class="card">
      <span>Points cumulés</span>
        <p>0</p>
      <span></span>
    </div>
    <div class="card">
      <span>Récompenses utilisés</span>
      <p>0</p>
      <span></span>
    </div>
  </div>

  <div class="main-content">
    <div class="program-container">
      <div class="program-header">
        <% if @fidelity_program.present? %>
          <p>Programme en cours</p>
          <div id="status-container" >
              <p>Statut</p>
              <div class="fp-on" id="green-round"></div>
          </div>
        <% end %>
      </div>
      <div class="text-program">
        <% if @fidelity_program.present? %>
          <h2><%= @fidelity_program.name %></h2>
        <% else %>
          <p>Vous n’avez pas encore créé votre programme de fidélité.</p>
        <%= link_to 'Aller sur programme', landing_path , class:"create-btn" %>
        <% end %>
        <% if @fidelity_program.present? %>
          <p> Actif depuis: <%= @fidelity_program.created.strftime("%d-%m-%Y") %></p>
        <% end %>
      </div>
    </div>
  </div>

</div>

  <% else %>

<div class="main-programm">
  <div class="programm-header">
    <h1>Mes programmes</h1>
    <div class="input-div">
      <input type="text" id="search-input", placeholder="Cherchez votre programme">
      <i class="fa-solid fa-magnifying-glass"></i>
    </div>
  </div>


    <% current_user.inscriptions.each do |i| %>
      <%= link_to fidelity_program_inscription_path(i.fidelity_program.id, i), class: "programm-container" do %>
        <div class="programm-btn">
          <div class="icon-con">
            <div class="ic-img">
              <%= image_tag 'infinity.png', alt:"logo programs" %>
            </div>
          </div>
          <%= content_tag(:span, i.fidelity_program.name, class:"programm-text") %>
          <i class="fa-solid fa-chevron-left chevron"></i>
        </div>
      <% end %>
    <% end %>

</div>
<% end %>

app/views/pages/landing.html.erb
<div class="main-landing">
  <div class="top-landing">
    <div class="text-landing">
      <p>Vous n’avez aucun programme en cours</p>
      <p id="p-landing" >Fidélisez vos clients.</p>
    </div>

    <div class="button-landing">
      <%= link_to "créer votre programme", new_fidelity_program_path, class:"create-btn" %>
    </div>
  </div>

  <div>
    <%= image_tag "landing.png", class:"img-landing" %>
  </div>
</div>