config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root to: "pages#home"

  resources :fidelity_programs do
    resources :rewards
    resources :inscriptions do
      resources :participations
    end
  end

  # --------------Route Fidelty Programme-----------------
  get "/customers", to: "fidelity_programs#show_clients", as: :customers
  get "/subscribe", to: "inscriptions#new", as: :subscribe
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/status", to: "inscriptions#status", as: :status_profile
  get "/etablissement", to: "pages#etablissement", as: "etablissement"
  get "/validations", to: "pages#validations", as: "validations"
  get "/settings", to: "pages#settings", as: "settings"
  get "/landing", to: "pages#landing", as: "landing"

  # --------------Route Customers-----------------

  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_scans", to: "pages#customers_scans", as: :customers_scans
  get "/customers_etablissement", to: "pages#customers_etablissement"

  # --------------Route Participation-----------------
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_rewards", to: "pages#customers_rewards", as: :customers_rewards
  get "/customers_etablissement", to: "pages#customers_etablissement"

  # --------------Route Participations-----------------
  post "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_rewards", to: "participations#redeem", as: :redeem_points
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/history", to: "inscriptions#history", as: :history
end

app/models/inscription.rb
class Inscription < ApplicationRecord
  belongs_to :user
  belongs_to :fidelity_program
  has_many :participations, dependent: :destroy
  has_many :rewards, through: :fidelity_program
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController

  def index
    @fidelity_programs = FidelityProgram.all
    @fidelity_program = FidelityProgram.find(params[:fidelity_program_id])
    @inscriptions = Inscription.all
    @sum = 0
  end

  def new
    @fidelity_program = FidelityProgram.find(params[:fidelity_program_id])
    @inscription = Inscription.new
  end

  def create
    @inscription = Inscription.new
    @inscription.user_id = current_user.id
    @inscription.fidelity_program_id = params[:fidelity_program_id]
    @inscription.created = DateTime.now.strftime "%d/%m/%Y %H:%M"
    if @inscription.save
      redirect_to fidelity_program_inscription_path(params[:fidelity_program_id], @inscription)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @participation = Participation.new
    @fidelity_program = FidelityProgram.find(params[:fidelity_program_id])
    @inscription = Inscription.find(params[:id])
    @sum = 0
  end

  def history
    @participation = Participation.new
    @fidelity_program = FidelityProgram.find(params[:fidelity_program_id])
    @inscription = Inscription.find(params[:id])
    @sum = 0
  end

  def status
    @fidelity_program = FidelityProgram.find(params[:fidelity_program_id])
    @inscription = Inscription.find(params[:id])
  end

  private

  def set_params
    params.require(:inscription).permit(:fidelity_program_id)
  end
end

app/helpers/inscriptions_helper.rb
module InscriptionsHelper
end

app/views/inscriptions/history.html.erb
<%= render 'shared/burger_menu' %>

<div class="s-i-head">
  <div class="container">
    <%= render 'shared/back_button' %>
    <div class="sih-info">
      <h1>Mon historique</h1>
      <p>Retrouvez la liste de vos points dépensés et acquis</p>
    </div>
  </div>
</div>

<div class="main-history" data-controller="history">

  <div class="status-bar">
    <div class="text-s-container">
      <div class="active-container" >
        <span data-history-target="add" data-action="click->history#secondChange" class="text-status active-text">Points reçus</span>
        <div class="active-bar" data-history-target="addbar" ></div>
      </div>
      <div class="active-container" >
        <span data-history-target="deduct" data-action="click->history#change" class="text-status" >Points utiisés</span>
        <div data-history-target="deductbar" ></div>
      </div>
    </div>
  </div>

  <div class="add-container" data-history-target="addmain">
    <% @inscription.participations.each do |event| %>
    <% if event.points > 0 %>
    <div class="transaction">
      <span class="date-value"><%= event.created.strftime "%d-%m-%Y" %></span>
      <div class="point-div">
        <span class="pt-add"><%= event.points %></span>
        <span class="mdi--star-four-points-circle" id="icon-add"></span>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>

  <div class="deduct-container hidden-main" data-history-target="deductmain">
    <% @inscription.participations.each do |event| %>
    <% if event.points < 0 %>
    <%= link_to fidelity_program_inscription_participation_path(@fidelity_program, @inscription, event.id),class:"transaction" do %>
      <%= image_tag 'QRCode.svg', alt:"image de qrcode" %>
      <span class="date-value"><%= event.created.strftime "%d-%m-%Y" %></span>
      <div class="point-div">
        <span class="pt-value"><%= event.points %></span>
        <span class="mdi--star-four-points-circle" id="icon-pt"></span>
      </div>
    <% end %>
    <% end %>
    <% end %>
  </div>

</div>

app/views/inscriptions/new.html.erb
<div id="container-inscription">

    <div id="header-inscription">
      <div>
        <p>Bienvenue dans le programme de <%= @fidelity_program.name %></p>
      </div>
    </div>


  <div>
    <%= form_tag(fidelity_program_inscriptions_path(@fidelity_program), method: :post) do %>
    <%= submit_tag("Continuer", id: "button-inscription") %>
    <% end %>
  </div>
</div>

app/views/inscriptions/show.html.erb
<%= render 'shared/burger_menu' %>

<div class="s-i-head">
  <div class="container">

  <%= render 'shared/back_button' %>

    <div class="sih-info">
    <h1><%= @inscription.fidelity_program.name %></h1>
    <p><%= @inscription.fidelity_program.user.business_name %></p>
    </div>
  </div>
</div>

<div id="s-i-body" class="container">
  <div id="sib-title">
    <p>Mes points<p>
  </div>
  <div id="sib-points">
    <div id="sib-number">
      <% @inscription.participations.each do |participation| %>
      <% @sum += participation.points %>
      <% end %>
      <%= @sum %>
    </div>
  </div>
</div>

<div id="s-i-btns" class="container"  data-controller="photo-input">
  <div id="si-rewards">
    <%= link_to "Mes récompenses", customers_rewards_path, class: "td-none" %>
  </div>
  <div id="si-history">
    <div class="upload-container" >
      <button id="custom-upload-button" class ="btn-pics" data-photo-input-target="button" display="block" data-action="click->photo-input#addPhoto">Choisir une photo</button>
      <%= simple_form_for [@fidelity_program, @inscription, @participation], enctype:"multipart/form-data"  do |f| %>
        <%= f.input :photo, as: :file, label: false, input_html:{id:"photo-upload", data:{ photo_input_target: "photo"}, class: "hidden-input"} %>
        <%= f.submit "Valider", style: "display: none", data:{ photo_input_target: "validate"} %>
      <% end %>
    </div>
  </div>


  <div id="file-check" style="display: none;" data-photo-input-target="check">
    <i class="fa-solid fa-check"></i>
    <span id="file-name" data-photo-input-target="file"></span>
  </div>
</div>

app/views/inscriptions/status.html.erb
<h1>Participation ajoutée !</h1>

<p>nom du programme</p>
<%= @inscription.fidelity_program.name %>

<% if @inscription.participations.last.points < 0 %>
  <p><%= (@inscription.participations.last.points).abs %> points ont été déduits
  </p>
<% else %>
  <p><%= (@inscription.participations.last.points).abs %> points ont été ajoutés</p>
<% end %>

<%= link_to "Back", fidelity_program_inscription_path(@fidelity_program, @inscription) %>