config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root to: "pages#home"

  resources :fidelity_programs do
    resources :rewards
    resources :inscriptions do
      resources :participations
    end
  end

  # --------------Route Fidelty Programme-----------------
  get "/customers", to: "fidelity_programs#show_clients", as: :customers
  get "/subscribe", to: "inscriptions#new", as: :subscribe
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/status", to: "inscriptions#status", as: :status_profile
  get "/etablissement", to: "pages#etablissement", as: "etablissement"
  get "/validations", to: "pages#validations", as: "validations"
  get "/settings", to: "pages#settings", as: "settings"
  get "/landing", to: "pages#landing", as: "landing"

  # --------------Route Customers-----------------

  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_scans", to: "pages#customers_scans", as: :customers_scans
  get "/customers_etablissement", to: "pages#customers_etablissement"

  # --------------Route Participation-----------------
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_rewards", to: "pages#customers_rewards", as: :customers_rewards
  get "/customers_etablissement", to: "pages#customers_etablissement"

  # --------------Route Participations-----------------
  post "/fidelity_programs/:fidelity_program_id/inscriptions/:id/customers_rewards", to: "participations#redeem", as: :redeem_points
  get "/fidelity_programs/:fidelity_program_id/inscriptions/:id/history", to: "inscriptions#history", as: :history
end

app/models/fidelity_program.rb
class FidelityProgram < ApplicationRecord
  include Abyme::Model
  
  belongs_to :user
  has_many :rewards, dependent: :destroy
  has_many :inscriptions, dependent: :destroy
  accepts_nested_attributes_for :rewards
  has_one_attached :qrcode, dependent: :destroy
  abymize :rewards

  accepts_nested_attributes_for :rewards, allow_destroy: true

  before_commit :remove_empty_reward, on: :create

  private

  def remove_empty_reward
    rewards.each do |reward|
      reward.destroy if reward.description.blank?
    end
  end
end

app/controllers/fidelity_programs_controller.rb
class FidelityProgramsController < ApplicationController
  before_action :find_id, only:[:edit, :show, :update, :destroy]


  def nav
    @fidelity_programs = FidelityProgram.all
  end

  def index
    @fidelity_programs = FidelityProgram.all
  end

  def landing
  end

  def new
    @fidelity_programs = FidelityProgram.all
    @fidelity_program = FidelityProgram.new
    @fidelity_program.rewards.build
  end

  def create
    @fidelity_program = FidelityProgram.new(set_params)
    @fidelity_program.user = current_user
    @fidelity_program.created = DateTime.now.strftime "%d/%m/%Y %H:%M"
    @fidelity_program.active = true

    if params[:rewards_attributes]
      @fidelity_program.rewards.build
      format.html { render :new, status: :unprocessable_entity }
    end

    respond_to do |format|
      if params[:rewards_attributes]
        @fidelity_program.rewards.build
        format.html { render :new, status: :unprocessable_entity }
        @fidelity_program.save
      else
        if @fidelity_program.save
          format.html { redirect_to @fidelity_program }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
    @fidelity_program.save!
  end

  def show
    qrcode_url = "#{request.protocol}#{request.host}#{new_user_registration_path}?id=#{params[:id]}"
    @qrcode = RQRCode::QRCode.new(qrcode_url)
    @svg = @qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 3,
      standalone: true,
      use_path: true
    )
  end

  def edit
  end

  def update

    if @fidelity_program.update(set_params)
      redirect_to fidelity_program_path(@fidelity_program)
    else
      render :new,status: :unprocessable_entity
    end
  end

  def destroy
    @fidelity_program.destroy
    redirect_to root_path, status: :see_other
  end

  def show_clients
    @fidelity_program = current_user.fidelity_program
    @inscriptions = Inscription.all
    @users = User.all
    @sum = 0
  end

  private

  def set_params
    params.require(:fidelity_program).permit(:name, :points_per_euro, :qrcode, rewards_attributes: [:id, :name, :description, :points_required, :_destroy])
  end

  def find_id
    @fidelity_program = FidelityProgram.find(params[:id])
  end

end

app/helpers/fidelity_programs_helper.rb
module FidelityProgramsHelper
end

app/views/fidelity_programs/brouillon.html.erb
<!-- Récompenses -->
      <div class="reward-container">
        <div class="reward-text">
          <h3>Le produit offert</h3>
        </div>
        <div>
          <%= f.abyme_for(:rewards, partial: 'abyme/rewards_fields') do |abyme| %>
            <%= abyme.records %>
            <%= abyme.new_records %>
          <% end %>
        </div>
      </div>

      <!-- Bouton d'enregistrement -->
      <div class="submit-container">
        <%= f.submit 'Enregistrer', class: 'submit-button' %>
      </div>

app/views/fidelity_programs/edit.html.erb
<div class="main-form">

  <div class="form-container">
    <div class="timeline">
      <div class="circle" id="on"></div>
      <div class="bar"></div>
      <div class="circle"></div>
    </div>

    <div class="form-text">
      <h2>Editer</h2>
      <p>Modifier les informations de votre programme.</p>
    </div>
  </div>

  <div class="form-input">
    <%= simple_form_for @fidelity_program do |f| %>
      <!-- Nom du programme -->
      <div class="input-container first-input">
        <p>Nom du programme</p>
        <%= f.input :name, label: false, placeholder:"Le meilleur programme..." %>
      </div>

      <!-- Ratio euro/points -->
      <div class="input-container">
        <p>Ratio Euro/Points</p>
        <div class="ratio-container">
          <div class="euro-container">
            <p>1€</p>
          </div>
          <i class="fa-solid fa-equals"></i>
          <%= f.input :points_per_euro, label: false, placeholder:" 1 point" %>
        </div>
      </div>

      <!-- Récompenses -->
      <div class="reward-container">
        <div class="reward-text">
          <h3>Le produit offert</h3>
        </div>
        <div>
          <%= f.abyme_for(:rewards, partial: 'abyme/rewards_fields') do |abyme| %>
            <%= abyme.records %>
            <%= abyme.new_records %>
          <% end %>
        </div>
      </div>

      <!-- Bouton d'enregistrement -->
      <div class="submit-container">
        <%= f.submit 'Valider les modifications', class: 'submit-button' %>
      </div>
    <% end %>
  </div>

</div>

app/views/fidelity_programs/index.html.erb
<div class="program-container">
  <h1>Programmes</h1>

  <div class="program-content">
    <div>
      <ul style="list-style-type: none">
        <% @fidelity_programs.each do |program| %>
        <li><%= link_to "#{program.name}", fidelity_program_path(program), class: "link" %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <button class="btn-program">
    <%= link_to "Créer un programme", new_fidelity_program_path, style: "text-decoration: none; color: white" %>
  </button>

  <%= link_to "Back", root_path, class: "link" %>

</div>

app/views/fidelity_programs/new.html.erb
<div class="main-form">

  <div class="timeline">
    <div class="circle" id="on"></div>
    <div class="bar"></div>
    <div class="circle"></div>
  </div>

  <div class="form" data-controller="form">
    <%= simple_form_for @fidelity_program do |f| %>
      <div id="step1" data-form-target="step1">
        <div class="form-container">
          <div class="form-text">
            <h2>Programme Infos</h2>
            <p>Remplissez les informations pour le profil. Cela prendra quelques minutes. Vous aurez seulement besoin d'un passeport.</p>
          </div>

          <div class="form-input">
            <div class="input-container first-input">
              <p>Nom du programme</p>
              <%= f.input :name, label: false, placeholder:"Le meilleur programme..." %>
            </div>
            <div class="input-container">
              <p>Ratio Euro/Points</p>
              <div class="ratio-container">
                <div class="euro-container">
                  <p>1€</p>
                </div>
                <i class="fa-solid fa-equals"></i>
                <%= f.input :points_per_euro, label: false, placeholder:"1 point" %>
              </div>
            </div>
            <div class="btn-container">
              <%= link_to "Suivant", "#", data: { "form-target": "nextButton", action: "click->form#display" }, class: "submit-button next-btn" %>
            </div>
          </div>
        </div>
      </div>
      <div id="step2" class="hidden" data-form-target="step2">
        <div class="reward-container">
          <div class="reward-text">
            <h2>Les Récompenses</h2>
          </div>
          <div>
            <%= f.abyme_for(:rewards, partial: 'abyme/rewards_fields') do |abyme| %>
              <%= abyme.records %>
              <%= abyme.new_records %>
            <% end %>
          </div>
        </div>
        <div class="submit-container">
          <%= f.submit 'Enregistrer', class: 'submit-button', data: { action: "submit->form#submitForm" } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/fidelity_programs/show.html.erb
<div id="fp-s-main-container">
  <div id="fp-s-buttons">
    <%= link_to "Supprimer", fidelity_program_path(@fidelity_program), data: {turbo_method: :delete, turbo_confirm: "Confirmer la suppression du programme ?"}, class: "fp-s-delete" %>
    <%= link_to "Editer", edit_fidelity_program_path(@fidelity_program), class: "fp-s-edit", data: {turbo: :false} %>
  </div>

  <div id="fp-s-name">
    <h1><%= @fidelity_program.name.upcase %></h1>
    <div id="fp-status">
      <p>Statut</p>
      <div >
        <% if @fidelity_program.active = true %>
        <div class="fp-on"></div>
        <% else %>
        <div class="fp-off"></div>
        <% end %>
      </div>
    </div>
  </div>

  <div id="fp-s-left-info">
    <div id="fpsli-date">
      <% if @fidelity_program.created == nil %>
        <p>N/A</p>
        <% else %>
        <p>Créé le : <%= @fidelity_program.created.strftime "%d/%m/%Y" %></p>
        <% end %>
    </div>
    <div id="fpsli-ratio">
      <p>Ratio points/euros : 1€ = <%= @fidelity_program.points_per_euro %> points</p>
    </div>
  </div>

  <div id="fp-s-content">
        <div id="fp-s-info">

          <div id="fp-s-qr-container">
            <div id="fp-s-qr-text">
              Présentez à vos clients :
            </div>
            <div id="fp-s-qrcode">
              <%= @svg.html_safe %>
            </div>
          </div>
        </div>

    <div id="fp-s-cards">
      <% @fidelity_program.rewards.each do |reward| %>
      <div id="fp-s-card">
        <div id="fp-s-icon">
          <div class="image-wrapper">
            <%= image_tag reward.name.downcase == "boisson" ? "boisson.png" : "sushi2.png" %>
          </div>
        </div>
        <div id="fp-s-card-info">
          <div id="fpsci-name">
            <%= reward.name.upcase %>
          </div>
          <div id="fp-s-card-pts">
            <p>pour <div class="reward-points-required"><%= reward.points_required %></div> PTS</p>
          </div>
        </div>
      </div>
      <% end %>
    </div>

</div>
</div>

app/views/fidelity_programs/show_clients.html.erb
<div class="customer-container">
  <h1>Liste des clients </h1>

  <div id="header-user">
      <div id="email">
        <div class="c-header">
          Email
        </div>
        <div class="c-body">
          <% @fidelity_program&.inscriptions&.each do |i| %>
              <div class="c-content">
                <p><%= i.user.email %></p>
              </div>
          <% end %>
        </div>
      </div>
      <div id="inscription">
        <div class="c-header">
          Date d'inscription
        </div>
        <div class="c-body">
            <% @fidelity_program&.inscriptions&.each do |user| %>
              <div class="c-content">
              <% if user.created == nil %>
              <p>N/A</p>
              <% else %>
              <p><%= user.created.strftime("%d-%m-%Y") %></p>
              <% end %>
              </div>
          <% end %>
        </div>
      </div>
      <div id="points">
        <div class="c-header">
          <p>Points</p>
        </div>
        <div class="c-body">
            <% @fidelity_program&.inscriptions&.each do |i| %>
              <% i.participations.each do |p| %>
                <p><% @sum += p.points %></p>
              <% end %>
                <div class="c-content">
                  <p>
                  <%= @sum %>
                  </p>
                </div>
          <% end %>
        </div>
      </div>
  </div>
</div>